### PR TITLE
Add apply/4 function

### LINKED ISSUE #20: Support giving fwup a file and letting it use it directly
Since fwup can process a file path directly, it would be nice to use that rather than asking users to do something like:

```elixir
{:ok, fwup} = Fwup.stream(self(), args)

new_firmwmare_path
|> File.stream!([:bytes], 4096)
|> Stream.map(fn chunk ->
   Fwup.send_chunk(fwup, chunk)
end)
|> Stream.run()
```

This should also be faster.

### PR DESCRIPTION
**Pull request by ConnorRigby**
Allows calling fwup without needing a stream

Fixes #20

### CODE REVIEW

**Comment by fhunleth** [comment]
What do you think about having this send similar progress, finished, info etc. messages to when you stream?

**Comment by ConnorRigby** [comment]
@fhunleth just updated the apply/3 function to send progress messages.

**Review by fhunleth — APPROVED** [review]
I can't believe that was it. I had to read the code a couple times to believe it. 

The API feels a little weird since `stream/3` does basically the same thing except takes the arguments a different way. I mean, now that I see this, is `apply/4` just a convenience method to `stream/3`?

**Comment by ConnorRigby** [comment]
> is apply/4 just a convenience method to stream/3
yeah. the `Stream` module and function might not be the best name..

**Pull request merged**
